### Basically we need to convert the text into the format wich could be understand by the machine learning algorithms and deep learning algorithms .

In [1]:
from nltk.tokenize import sent_tokenize,word_tokenize
from nltk.corpus import stopwords

In [2]:
corpus='India, officially the Republic of India, is a country in South Asia. It is the seventh-largest country by area, the second-most populous country, and the most populous democracy in the world. Bounded by the Indian Ocean on the south, the Arabian Sea on the southwest, and the Bay of Bengal on the southeast, it shares land borders with Pakistan to the west; China, Nepal, and Bhutan to the north; and Bangladesh and Myanmar to the east. In the Indian Ocean, India is in the vicinity of Sri Lanka and the Maldives; its Andaman and Nicobar Islands share a maritime border with Thailand, Myanmar and Indonesia.'

### 1. Stop Words Removal

In [44]:
words=[]
for word in word_tokenize(corpus):
    if(word.lower() not in stopwords.words('English')) and (len(word)>=2):
        words.append(word.lower())

# without stopwords    
words_all=[]
for word in word_tokenize(corpus):
    if (len(word) == 1):
        if ((ord(word) >= 97 and ord(word) <= 122) or (ord(word) >= 65 and ord(word) <= 90)):
            words_all.append(word.lower())
    else:
        words_all.append(word.lower())

print('Total Stopwords present:',abs(len(words_all)-len(words)))

Total Stopwords present: 51


### 2. Creating Vocab

In [45]:
print(len(words))
vocab=list(set(words))
print(len(vocab))
vocab_all= list(set(words_all))
print(len(vocab_all))

54
45
58


### 3. Creating Encoders and Decoders

In [29]:
num=1
word_to_num={}
num_to_word={}

for word in vocab:
    word_to_num[word]=num
    num_to_word[num]=word
    num+=1

print(word_to_num['india'])

40


### 4. Encoding Sentences

In [34]:
data = []

for sent in sent_tokenize(corpus):
    temp = []
    for word in word_tokenize(sent):
        if (word.lower() not in stopwords.words('english') and (len(word) >= 2)):
          #print(word, end = ' ')
            temp.append(word_to_num[word.lower()])
    # print()            
    print(temp)
    
    data.append(temp)

[40, 13, 38, 40, 28, 31, 43]
[20, 28, 30, 35, 15, 28, 15, 26, 45]
[19, 16, 9, 31, 42, 27, 33, 22, 1, 34, 3, 2, 25, 44, 17, 32, 37, 29, 24, 4, 6, 23]
[16, 9, 40, 5, 41, 11, 8, 7, 18, 39, 21, 36, 12, 14, 6, 10]


### 5.Decoding the data

In [35]:
for sent in data:
    for word in sent:
        print(num_to_word[word], end = ' ')
    print()

india officially republic india country south asia 
seventh-largest country area second-most populous country populous democracy world 
bounded indian ocean south arabian sea southwest bay bengal southeast shares land borders pakistan west china nepal bhutan north bangladesh myanmar east 
indian ocean india vicinity sri lanka maldives andaman nicobar islands share maritime border thailand myanmar indonesia 


In [37]:
for i in [39,42,29,13,35,29,17]:
    print(num_to_word[i])

islands
arabian
bhutan
officially
second-most
bhutan
west


## One Hot Encoding.
This technique is used for encoding the wordsin some sort of numbers, including the sentences into the numerical data in sort to perform some mathemarical operations or computations on it .

<b>Process:</b> we first need to find the number of uniquq words in it and then define the sequncen of the words which remains cnostan throughout then arrange the zero and one as per the words in prsent in th esentences accorsing to the sequnce defined.

The lenght of the sequnce deifned is hte number of the unique words present in the corpus and each sentence needs to coded in that length only whih is fixed (could it be a flaw).

 ['all','at', 'bad', 'not','its'] <br>
'its not bad at all' [1 , 1 , 1 , 1 , 1] 'its not bad' [0 , 0 , 1 , 1 , 1] 'its bad' [0 , 0 , 1 , 0 , 1] 'not bad at all' [1 , 1 , 1 , 1 , 0]

In [46]:
import pandas as pd
from nltk.tokenize import word_tokenize, sent_tokenize

corpus = 'GeeksforGeeks is not a website or a company. GeeksforGeeks is a coding environment. Thats what i love. Which is good. Not bad at all'

### 1. Finding the sequence.


In [47]:
seq = set()

for word in word_tokenize(corpus):
    if(word != '.'):
        seq.add(word)
        
seq = list(seq)

print(seq)

['love', 'Thats', 'bad', 'all', 'is', 'Which', 'company', 'Not', 'not', 'GeeksforGeeks', 'a', 'at', 'good', 'website', 'what', 'environment', 'i', 'coding', 'or']


### 2. Finding Index to Encode

In [48]:
data = []

for sent in sent_tokenize(corpus):
    index = []
    for word in word_tokenize(sent):
        if(word != '.'):
            index.append(seq.index(word))
            
    data.append(index)

### 3. Encode the Sentances in One Hot Encoding Format

In [49]:
fin = []

for indexes in data:
    enc = [0 for x in range(len(seq))]
    for index in indexes:
        enc[index] = 1
    fin.append(enc)

### 4.Creating the DataFrame / Dataset

In [50]:
df = pd.DataFrame(fin, columns = seq)
df['Sentances_'] = sent_tokenize(corpus)
df.head()

love  Thats  bad  all  is  Which  company  Not  not  GeeksforGeeks  a  at  \
0     0      0    0    0   1      0        1    0    1              1  1   0   
1     0      0    0    0   1      0        0    0    0              1  1   0   
2     1      1    0    0   0      0        0    0    0              0  0   0   
3     0      0    0    0   1      1        0    0    0              0  0   0   
4     0      0    1    1   0      0        0    1    0              0  0   1   

   good  website  what  environment  i  coding  or  \
0     0        1     0            0  0       0   1   
1     0        0     0            1  0       1   0   
2     0        0     1            0  1       0   0   
3     1        0     0            0  0       0   0   
4     0        0     0            0  0       0   0   

                                     Sentances_  
0  GeeksforGeeks is not a website or a company.  
1        GeeksforGeeks is a coding environment.  
2                            Thats what i love.  
3                                Which is good.  
4                                Not bad at all

NOTE: Flaws

### using prebuild model from sklearn

### 1. Adding one word at a time.

In [1]:
import pandas as pd 
text=['a','b','c','d','e','c','b']
data= pd.get_dummies(text)
print(data)
print('--'*8)
print(data.keys())

       a      b      c      d      e
0   True  False  False  False  False
1  False   True  False  False  False
2  False  False   True  False  False
3  False  False  False   True  False
4  False  False  False  False   True
5  False  False   True  False  False
6  False   True  False  False  False
----------------
Index(['a', 'b', 'c', 'd', 'e'], dtype='object')


### 2. Whole sentence at a time.

we will use the one hot encoder from sklearn where encoder input is (1,1) shaped . so we will first reshape the daat to that from and further use the pre-built one hot encoder.

In [10]:
import numpy as np
from sklearn.preprocessing import OneHotEncoder

text = ['i love dogs', 'i hate cats', 'i like turtles', 'i love the dogs']
text= np.reshape(text,(-1,1))

encoder_=OneHotEncoder()
encoder_.fit(text)

one_hot = encoder_.transform(text)

print(one_hot.toarray())
print([i[3:]for i in encoder_.get_feature_names()])

[[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]


AttributeError: 'OneHotEncoder' object has no attribute 'get_feature_names'

In [13]:
import numpy as np
from sklearn.preprocessing import OneHotEncoder

text = ['i love dogs', 'i hate cats', 'i like turtles', 'i love the dogs']

text = np.reshape(text, (-1, 1))


encoder = OneHotEncoder()
encoder.fit(text)

one_hot = encoder.transform(text)

print(one_hot.toarray())
print(encoder_.get_feature_names_out())
print([i[3:]for i in encoder.get_feature_names_out()])

[[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]
['x0_i hate cats' 'x0_i like turtles' 'x0_i love dogs'
 'x0_i love the dogs']
['i hate cats', 'i like turtles', 'i love dogs', 'i love the dogs']


### 3. Tokenized Sentence.

In [25]:

text = [['this' ,'is' ,'good'], ['but','its','fine']]

print(np.shape(text))

## its fot the format of(-1,1)
## so we need to process directly 
encoder=OneHotEncoder()
one_hot=encoder.fit_transform(text)

print(one_hot.toarray())
print('--'*8)
print(i[3:] for i in encoder.get_feature_names_out())

(2, 3)
[[0. 1. 1. 0. 0. 1.]
 [1. 0. 0. 1. 1. 0.]]
----------------
<generator object <genexpr> at 0x0000024C16AEBCA0>


#### To dataframe.

In [29]:
import pandas as pd
df= pd.DataFrame(one_hot.toarray(),columns= [i[3:] for i in encoder.get_feature_names_out()])
df

but  this   is  its  fine  good
0  0.0   1.0  1.0  0.0   0.0   1.0
1  1.0   0.0  0.0  1.0   1.0   0.0

## Bag of Words

Bag of Words (BoW) is a simple and widely used text representation technique. It is used to convert text data (such as sentences) into numerical format, which can then be fed into machine learning algorithms. The key idea behind BoW is to represent text as a collection (or "bag") of words, without considering grammar or word order but keeping track of word frequencies.

In [35]:
import pandas as pd
feature_names=[]
word_text = ["The is a very very cute cat", "The dog is very cute"]

tokens=[token .split() for token in word_text]
vocab=list(set([word for text in tokens for word in text]))

for text in tokens:
    temp_vector=[0]*len(vocab)
    for word in text:
        temp_vector[vocab.index(word)]=text.count(word)
    feature_names.append(temp_vector)

df=pd.DataFrame(feature_names,columns=vocab)
df['Sentence']=word_text
df

a  cat  dog  cute  is  The  very                     Sentence
0  1    1    0     1   1    1     2  The is a very very cute cat
1  0    0    1     1   1    1     1         The dog is very cute

### Binary Bag of Words.

In [39]:
import pandas as pd

feature_vectors = []

word_text = ["The is a very very cute cat", "The dog is very cute"]  

tokens=[token.split() for token in word_text]

vocab = list(set([word for text in tokens for word in text]))

for text in tokens:
    temp_vector=[0]*len(vocab)
    for word in text:
        if word in vocab:
            temp_vector[vocab.index(word)]=1
    feature_vectors.append(temp_vector)

df_1 = pd.DataFrame(feature_vectors , columns=vocab)
df_1['Sentence']=word_text
df_1

a  cat  dog  cute  is  The  very                     Sentence
0  1    1    0     1   1    1     1  The is a very very cute cat
1  0    0    1     1   1    1     1         The dog is very cute

##  Count Vectorisation

### 1. Fitting and Transform seprately.

In [41]:
from sklearn.feature_extraction.text import CountVectorizer
from pandas import DataFrame

text_data  = [ "GFG is providing a new Deep Learning Course which is really good",
               "We will be studying Deep Learning from today",
               "I want a Deep sleep today"]

vec = CountVectorizer()
vec = vec.fit(text_data)

data_transformed = vec.transform(text_data)

df = DataFrame(data_transformed.toarray(), columns = vec.vocabulary_)
df

gfg  is  providing  new  deep  learning  course  which  really  good  we  \
0    0   1          1    0     1         1       2      1       1     1   1   
1    1   0          1    1     0         0       0      1       0     0   0   
2    0   0          1    0     0         0       0      0       0     0   0   

   will  be  studying  from  today  want  sleep  
0     0   0         0     0      0     1      0  
1     0   1         1     0      1     0      1  
2     1   0         1     1      0     0      0

### 2. Dealing with various properties

In [44]:
vec=CountVectorizer( ngram_range=(1, 1), stop_words=('english'),   lowercase=True)
vec=vec.fit(text_data)
transformed=vec.transform(text_data)
df= DataFrame(transformed.toarray(),columns= vec.vocabulary_)
df

gfg  providing  new  deep  learning  course  really  good  studying  today  \
0    1          1    1     1         1       1       1     1         0      0   
1    0          1    0     0         1       0       0     0         0      1   
2    0          1    0     0         0       0       0     0         1      0   

   want  sleep  
0     0      0  
1     1      0  
2     1      1

### 3. Chracter level Encoding

In [46]:
vec=CountVectorizer( ngram_range=(1, 1),lowercase=True,analyzer='char')
vec=vec.fit(text_data)
transformed=vec.transform(text_data)
df= DataFrame(transformed.toarray(),columns= vec.vocabulary_)
df

g  f     i  s  p  r  o  v  d  ...  e  w  l  c  u  h  y  b  t  m
0  11  3  0  2  3  6  1  5  2  6  ...  4  4  2  4  3  0  1  1  2  1
1   7  2  1  0  3  5  1  2  0  3  ...  3  2  1  2  1  2  1  0  2  2
2   5  3  0  0  2  4  0  0  0  1  ...  1  1  2  0  1  2  0  0  1  1

[3 rows x 22 columns]

#### From Scratch building (chracter level encoding)

In [48]:
text_data = ["This is a sample sentence", "Another example sentence", "One more text sentence",'this']

characters = list(set(''.join(text_data)))
print(len(characters))

chr_to_int = {i : indx  for indx , i in enumerate(characters)}

enc_data = [[chr_to_int[char] for char in sent] for sent in text_data]
print(enc_data)

18
[[3, 12, 14, 5, 4, 14, 5, 4, 0, 4, 5, 0, 10, 11, 9, 1, 4, 5, 1, 13, 6, 1, 13, 17, 1], [2, 13, 8, 6, 12, 1, 15, 4, 1, 16, 0, 10, 11, 9, 1, 4, 5, 1, 13, 6, 1, 13, 17, 1], [7, 13, 1, 4, 10, 8, 15, 1, 4, 6, 1, 16, 6, 4, 5, 1, 13, 6, 1, 13, 17, 1], [6, 12, 14, 5]]


#### From Scratch Decoding

In [49]:
int_to_chr = {indx : i  for indx , i in enumerate(characters)}

dec_data = [''.join([int_to_chr[char] for char in sent]) for sent in end_data]
print(dec_data)

['This is a sample sentence', 'Another example sentence', 'One more text sentence', 'this']


## TF_IDF 

TF-IDF (Term Frequency - Inverse Document Frequency) is a statistical measure used to evaluate the importance of a word in a document relative to a collection of documents (corpus). It’s commonly used in text mining and information retrieval.

Here's how TF-IDF works:

Term Frequency (TF): This measures how frequently a term (word) appears in a document.<br>

TF(𝑡,𝑑)=Number of times term 𝑡 appears in document 𝑑 / Total number of terms in document  𝑑 <br>

Inverse Document Frequency (IDF): This measures the importance of the term in the entire corpus. It helps to down-weight terms that appear very frequently across documents (e.g., common words like "the" or "and").
<br>
IDF(𝑡,𝐷)=log(
Total number of documents in corpus 𝐷/
Number of documents containing term 𝑡
)
<br>
TF-IDF: The final value is the product of TF and IDF:

TF-IDF(t,d,D)=TF(t,d)×IDF(t,D)

This score indicates the importance of a term in a specific document relative to the entire corpus.

Example
Suppose you have a corpus with three documents:<br>

Doc 1: "Deep learning is powerful."<br>
Doc 2: "Machine learning is a subset of AI."<br>
Doc 3: "AI is the future of technology."<br>
Let’s calculate the TF-IDF for the term “learning” in the first document:<br>

TF for "learning" in Doc 1 = 1/4 (because "learning" appears once in a total of 4 words).<br>
IDF for "learning" = log(3/2) (since "learning" appears in 2 out of the 3 documents).<br>
TF-IDF for "learning" in Doc 1 = (1/4) * log(3/2).<br>
This process is repeated for each term in each document, resulting in a vector of TF-IDF values for the document.<br>



In [54]:
import numpy as np 
import pandas as pd 

text_data=["good movie", "bad movie", "good bad movie"]

# Sentences and Word Tokenization
word_data = [sentence.split(' ') for sentence in text_data]
# print(word_data)
# Finding the Vocab
vocab = list(set([word for sentence in word_data for word in sentence]))
# print(vocab)

# Finding Term Frequency
tf_data = []
for sentence in word_data:
    tf_sentence = []
    for word in vocab:
        tf_sentence.append(sentence.count(word)/len(sentence))
    tf_data.append(tf_sentence)

# print(tf_data)

n_documents = len(text_data)
idf_data = []
for word in vocab:  
    n_appearances = 0
    for sentence in word_data:
        if word in sentence:
            n_appearances += 1

    idf = np.log(n_documents/n_appearances)
    idf_data.append(idf)  
# print(idf_data)

# Finding TF-IDF for each sentence
tfidf_data = []
for tf_sentence in tf_data:
    tfidf_sentence = []
    for tf, idf in zip(tf_sentence, idf_data):
        tfidf_sentence.append(tf*idf)
    tfidf_data.append(tfidf_sentence)
    
df = pd.DataFrame(tfidf_data, columns = vocab)
df['full_sent'] = text_data

df

good  movie       bad       full_sent
0  0.202733    0.0  0.000000      good movie
1  0.000000    0.0  0.202733       bad movie
2  0.135155    0.0  0.135155  good bad movie

   ### With sklearn

In [55]:
# Finding TF-IDF for each sentence
tfidf_data = []
for tf_sentence in tf_data:
    tfidf_sentence = []
    for tf, idf in zip(tf_sentence, idf_data):
        tfidf_sentence.append(tf*idf)
    tfidf_data.append(tfidf_sentence)
    
df = pd.DataFrame(tfidf_data, columns = vocab)
df['full_sent'] = text_data

df

good  movie       bad       full_sent
0  0.202733    0.0  0.000000      good movie
1  0.000000    0.0  0.202733       bad movie
2  0.135155    0.0  0.135155  good bad movie

In [57]:
vec.get_feature_names_out()

array([' ', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'l', 'm', 'n',
       'o', 'p', 'r', 's', 't', 'u', 'v', 'w', 'y'], dtype=object)

### TF_IDF on Data

In [58]:
import re
import nltk
import joblib
import pandas as pd
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

nltk.download('stopwords')
nltk.download('punkt')

stemmer = PorterStemmer()

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\deeps\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\deeps\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


### Import The Data

In [59]:
df = pd.read_csv('twitter_validation.csv', header = None)
df = df.rename({0 : 'id', 1 : 'company', 2 : 'sentiment', 3 : 'raw_tweet'}, axis = 1)

df = df[df['sentiment'] != 'Irrelevant']
df = df[df['sentiment'] != 'Neutral']

tweets = df['raw_tweet'].values

### Text Preprocessing 

In [60]:
processed_tweets = []

for tweet in tweets:
    
    tweet = re.sub(r'[^a-zA-Z]',' ',tweet)    
    tweet = tweet.lower()
    tweet = [word for word in tweet.split(' ') if not word in stopwords.words('english')]
    tweet = [stemmer.stem(word) for word in tweet]
    tweet = [word for word in tweet if len(word) != 0]
    tweet = ' '.join(tweet)

    processed_tweets.append(tweet)

### TF_IDF


In [62]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()

enc_tweets = tfidf.fit_transform(processed_tweets)

df_ = pd.DataFrame(enc_tweets.toarray(), columns = tfidf.get_feature_names_out())
df_

abil  abl  absolut  absurd  access  accessibleatx  accomplish   account  \
0     0.0  0.0      0.0     0.0     0.0            0.0         0.0  0.000000   
1     0.0  0.0      0.0     0.0     0.0            0.0         0.0  0.000000   
2     0.0  0.0      0.0     0.0     0.0            0.0         0.0  0.193864   
3     0.0  0.0      0.0     0.0     0.0            0.0         0.0  0.000000   
4     0.0  0.0      0.0     0.0     0.0            0.0         0.0  0.000000   
..    ...  ...      ...     ...     ...            ...         ...       ...   
538   0.0  0.0      0.0     0.0     0.0            0.0         0.0  0.000000   
539   0.0  0.0      0.0     0.0     0.0            0.0         0.0  0.000000   
540   0.0  0.0      0.0     0.0     0.0            0.0         0.0  0.000000   
541   0.0  0.0      0.0     0.0     0.0            0.0         0.0  0.000000   
542   0.0  0.0      0.0     0.0     0.0            0.0         0.0  0.000000   

     aceofpyrit  achiev  ...  ziryhrf  zlcc  zone  zoom  zqw  ztc  ztl  zukf  \
0           0.0     0.0  ...      0.0   0.0   0.0   0.0  0.0  0.0  0.0   0.0   
1           0.0     0.0  ...      0.0   0.0   0.0   0.0  0.0  0.0  0.0   0.0   
2           0.0     0.0  ...      0.0   0.0   0.0   0.0  0.0  0.0  0.0   0.0   
3           0.0     0.0  ...      0.0   0.0   0.0   0.0  0.0  0.0  0.0   0.0   
4           0.0     0.0  ...      0.0   0.0   0.0   0.0  0.0  0.0  0.0   0.0   
..          ...     ...  ...      ...   ...   ...   ...  ...  ...  ...   ...   
538         0.0     0.0  ...      0.0   0.0   0.0   0.0  0.0  0.0  0.0   0.0   
539         0.0     0.0  ...      0.0   0.0   0.0   0.0  0.0  0.0  0.0   0.0   
540         0.0     0.0  ...      0.0   0.0   0.0   0.0  0.0  0.0  0.0   0.0   
541         0.0     0.0  ...      0.0   0.0   0.0   0.0  0.0  0.0  0.0   0.0   
542         0.0     0.0  ...      0.0   0.0   0.0   0.0  0.0  0.0  0.0   0.0   

      zy  zyot  
0    0.0   0.0  
1    0.0   0.0  
2    0.0   0.0  
3    0.0   0.0  
4    0.0   0.0  
..   ...   ...  
538  0.0   0.0  
539  0.0   0.0  
540  0.0   0.0  
541  0.0   0.0  
542  0.0   0.0  

[543 rows x 2499 columns]

### Saving the Model.

In [63]:
joblib.dump(tfidf, 'tfidf_model.joblib')

df.to_csv('tfidf_enc.csv', index = False)

print('Model is saved with name tfidf_model.joblib!')
print('Encodings are saved with name tfidf_enc.csv')

Model is saved with name tfidf_model.joblib!
Encodings are saved with name tfidf_enc.csv


In [65]:
joblib.load('tfidf_model.joblib')

TfidfVectorizer()